name: build and deploy
on:
  push: 
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@main
#       - name: Install dependencies
#         run: npm ci
#       - name: Build Dependencies
#         run: npm run build
      - name: Archive LMS Aungular App
        uses: actions/upload-artifact@main
        with:
          name: lmsapp
          path: client/dist
      - name: Archive LMS API
        uses: actions/upload-artifact@main
        with:
          name: api
          path: api
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download LMS App
        uses: actions/download-artifact@main
        with:
          name: lmsapp
          path: ./web/testlms.lmsleads.com/public_html
      - name: Download LMS API
        uses: actions/download-artifact@main
        with:
          name: api
          path: ./web/testlms.lmsleads.com/public_html/api
      - name: See Directories
        run: ls -R
      - name: Sync Files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ftp.mindtech.com.mx
          username: u529436459.menu-digital.mindtech.com.mx
          password: ${{ secrets.FTP_PASSWORD }}
